# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Finger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 650)
        Form.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(6, 190, 182, 155), stop:1 rgba(2, 142, 161, 255));")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 5, 640, 640))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(645, 20, 160, 610))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(188, 149, 198, 155), stop:1 rgba(125, 196, 204, 155));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font-size:21px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(103, 249, 212, 200), stop:1 rgba(255, 149, 84, 255));\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(200,200,200);\n"
"border-radius:10px\n"
"\n"
"")
        self.label.setMidLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("font-size:21px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(103, 249, 212, 200), stop:1 rgba(255, 149, 84, 255));\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(200,200,200);\n"
"border-radius:10px\n"
"\n"
"\n"
"")
        self.label_2.setMidLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("font-size:21px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(103, 249, 212, 200), stop:1 rgba(255, 149, 84, 255));\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(200,200,200);\n"
"border-radius:10px\n"
"")
        self.label_3.setMidLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("font-size:21px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(103, 249, 212, 200), stop:1 rgba(255, 149, 84, 255));\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(200,200,200);\n"
"border-radius:10px\n"
"\n"
"\n"
"")
        self.label_4.setMidLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("font-size:21px;\n"
"font-weight:bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(103, 249, 212, 200), stop:1 rgba(255, 149, 84, 255));\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(200,200,200);\n"
"border-radius:10px\n"
"")
        self.label_5.setMidLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frame.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Finger_Waves"))
        self.label.setText(_translate("Form", "thumb"))
        self.label_2.setText(_translate("Form", "index"))
        self.label_3.setText(_translate("Form", "middle"))
        self.label_4.setText(_translate("Form", "ring"))
        self.label_5.setText(_translate("Form", "little"))
